=== isabelmolinaji10/ejerciciosProgramacion/KK/ExamenXSD/Playa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="playa" type="tipoPlaya"/>
  <xs:complexType name="tipoPlaya">
  	<xs:sequence>
  		<xs:element name="personas" type="tipoPersonas" maxOccurs="unbounded"/>
  		<xs:element name="sombrillas" type="tipoSombrillas" maxOccurs="unbounded" />
  		<xs:element name="arena" type="tipoArena" maxOccurs="unbounded"/>
  		<xs:element name="chiringuitos" type="tipoChiringuitos"/>
  		<xs:element name="barcos" type="tipoBarcos"/>
  		<xs:element name="gabiotas" type="tipoGabiotas"/>
   	</xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="tipoSombrillas" mixed="true">
  	<xs:sequence>
  		<xs:element name="sombrilla" type="tipoSombrilla" maxOccurs="unbounded"/>
  	</xs:sequence>
  	<xs:attribute name="color" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="tipoSombrilla">
	<xs:attribute name="marca" type="xs:string"/>
	<xs:attribute name="aperturaMetros" type="xs:integer"/>
  </xs:complexType>
  
   <xs:complexType name="tipoGabiotas">
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="nombre" type="xs:string" />
        </xs:extension>
      </xs:simpleContent> 
    </xs:complexType>

<xs:complexType name="tipoBarcos">
  	<xs:choice>
  		<xs:element name="barco">
  			<xs:complexType>
  				<xs:attribute name="tipo">
  					<xs:simpleType>
  						<xs:restriction base="xs:string">
  							<xs:enumeration value="BergantÃ­n"/>
  							<xs:enumeration value="Bombardas"/>
  							<xs:enumeration value="Carabela"/>
  						</xs:restriction>
  					</xs:simpleType>
  				</xs:attribute>
  			</xs:complexType>
  		</xs:element>
  		<xs:element name="barcosMar">
  			<xs:complexType>
  				<xs:attribute name="cantidadBarcos">
  					<xs:simpleType>
  						<xs:restriction base="xs:integer">
  							<xs:minInclusive value="0"/>
  							<xs:maxInclusive value="100"/>
  						</xs:restriction>
  					</xs:simpleType>
  				</xs:attribute>
  			</xs:complexType>
  		</xs:element>
  	</xs:choice>
  </xs:complexType>
  
    <xs:complexType name="tipoArena">
  	<xs:all>
  		<xs:element name="longitud" type="xs:string"/>
  		<xs:element name="condicionesBano" type="xs:string"/>
  	</xs:all>
  </xs:complexType>
  
   <xs:complexType name="tipoArenaDerivado">
    <xs:complexContent>
      <xs:extension base="tipoArena">
        <xs:attribute name="localizacion" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="tipoPersonas">
  	<xs:attribute name="identificador">
  		<xs:simpleType>
  			<xs:restriction base="xs:string">
  				<xs:pattern value="[A-Z]{7}[0-9]{3}"/>
  			</xs:restriction>
  		</xs:simpleType>
  	</xs:attribute>
  	<xs:attribute name="matriculaCoche">
  		<xs:simpleType>
  			<xs:restriction base="xs:string">
  				<xs:pattern value="[0-9]{4}[A-Z]{3}"/>
  			</xs:restriction>
  		</xs:simpleType>
  	</xs:attribute>
  </xs:complexType>
  
	








</xs:schema>

=== isabelmolinaji10/ejerciciosProgramacion/KK/ExamenXSD/Playa.xml
<?xml version="1.0" encoding="UTF-8"?>
<playa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Playa.xsd">
	<personas identificador=IMOLJIM223 matriculaCoche=1234KNJ></personas>
	<sombrillas color="Amarillo">Hay 5 sombrillas amarillas <!-- Elemento mixto -->
		<sombrilla marca="Agatha Ruiz de la Prada" aperturaMetros="2"/> <!-- Elemento vacio -->
	</sombrillas>
	<chiringuitos></chiringuitos>
	<barcos>
		<barco tipo="Bombardas"/> <!-- Como es choice, o uno u otro -->
		<barcosMar cantidadBarcos="3"></barcosMar> <!-- numero dentro de un intervalo -->
	</barcos>
	<gabiotas nombre= "Las gabiotas blancas">5</gabiotas> <!-- elemento con atributos y contenido de tipo numÃ©rico -->
	<arena localizacion="Playa de la Caleta">
 		<longitud>450m</longitud>
 	</arena>



</playa>
