=== isabelmolinaji10/ejerciciosProgramacion/KK/src/ejercicio1.dtd
<!DOCTYPE placaBase [
<!ELEMENT placaBase (placa*)>
<!ELEMENT placa (microprocesador, memoria+, modelo, fabricante)>
<!ELEMENT microprocesador (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT fabricante (Intel|Asus)>
<!ELEMENT Intel EMPLY>
<!ELEMENT Asus EMPLY>
]>

<!-- <!ELEMENT placa (microprocesador | memoria | modelo |fabricante)*> Esto sirve para poner  lo que hay dentro del parentesis de forma desordenada -->

=== isabelmolinaji10/ejerciciosProgramacion/KK/src/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placaBase SYSTEM "ejercicio1.dtd">

<placaBase>
<placa>
    <microprocesador>Procesador Intel Core i7</microprocesador>
    <memoria>4Gb</memoria>
    <modelo>8500Y</modelo>
    <fabricante><Intel/></fabricante>
</placa>
<placa>
    <microprocesador>Asus ROG </microprocesador>
    <memoria>64Gb</memoria>
    <modelo>Rampage VI Apex</modelo>
    <fabricante><Asus/></fabricante>

</placa>


</placaBase>
